### PR TITLE
Update the Release & Update Policy page for 3.2.x

### PR DESCRIPTION
**Pull request by VSEphpbb**
Should not be merged until after phpBB 3.2.x is released.

To-do:
- [x] Add 3.3.x project name once decided
- [x] Finalize correct links to 3.2 and 3.1 downloads
- [x] Finalize planned dates for 3.1 EOM, EOL, and 3.2 and 3.3 dates

### CODE REVIEW

**Comment by marc1706** [comment]
Mind adding our new codename for 3.3.x?

**Comment by DavidIQ** [comment]
Can we be more explicit about what a contribution is? Maybe put next to it in parenthesis "(Extensions/Styles/Language packs)" or something to that effect.

**Comment by VSEphpbb** [comment]
@michaelcullum rdy to merge too?

**Comment by DavidIQ** [comment]
@michaelcullum needs merging

**Comment by michaelcullum** [comment]
Will run merge script shortly. :)

**Pull request merged**
