### PR TITLE
EPV display updates

### PR DESCRIPTION
**Pull request by VSEphpbb**
@DavidIQ & @paul999

### CODE REVIEW

**Comment by michaelcullum** [comment]
All prs with graphical changes require a screenshot. ;)

**Comment by VSEphpbb** [comment]
I can't run EPV from my local machine

**Comment by VSEphpbb** [comment]
Here's a photochop.
epvupdate
The unreadable darkred text is somehow created by EPV or Synfony, and needs to be fixed in EPV I think.

**Comment by michaelcullum** [comment]
This is fine by me. @paul999 Hit the green button if you're happy with this.

**Comment by VSEphpbb** [comment]
Requires https://github.com/phpbb/website-assets/pull/1

**Comment by paul999** [comment]
Merged both.

**Pull request merged**
