### PR TITLE
Extensions pages - updates for 3.2

### PR DESCRIPTION
**Pull request by battye**
I'll put any extensions changes relevant to the upcoming phpBB 3.2 release in this PR.

I've labelled it under both _awaiting review_ and _don't merge_ because I guess it makes sense to only pull the trigger on the merge when 3.2 has been officially released.

### CODE REVIEW

**Comment by battye** [comment]
First change, just a small one: 

Update the extension dev forum rules to include mention of a new topic prefix and the phpBB version in the topic template.

screen shot 2016-06-26 at 11 26 15 pm

**Comment by VSEphpbb** [comment]
If an extension **is** phpBB 3.2 specific...

**Comment by battye** [comment]
Fixed now, thanks @VSEphpbb

**Comment by DavidIQ** [comment]
@battye do you still need to do anything else in this merge request? Can it be merged or does it need a rework?

**Comment by DavidIQ** [comment]
Looks like this has conflicts now. Not sure how you want to proceed. Does this need closing?

**Pull request closed without merging**
