### PR TITLE
Add GSoC pages to .com

### PR DESCRIPTION
**Pull request by marc1706**
Todo:
- [x] Add link in top menu
- [x] Add instructions page
- [x] Add ideas page
- [x] Add Student Proposal Guidelines
- [x] Ensure assets are updated before merging

Depends on https://github.com/phpbb/website-assets/pull/11

Latest look: https://github.com/phpbb/phpbb-website/pull/107#issuecomment-276794152

### CODE REVIEW

**Comment by marc1706** [comment]
Current status of gsoc page:
image

**Comment by marc1706** [comment]
Ideas page so far:
image

**Comment by marc1706** [comment]
Current look of development page:
image

Current look of instructions page:
image

Current look of ideas page:
image

**Comment by marc1706** [comment]
Student proposal guidelines page:
image

**Comment by Derky** [comment]
Looks really good Marc!

I've the following suggestions:

**Project Ideas page**
1. Add an unordered list at the top for a quick overview of all ideas (including a #link) because the page has gotten quite long now.
2. Move the "Social share" idea below "Push notifications" because I think the other 3 ideas will draw more interest.
3. In the list remove the distinction between "Core Ideas" and "Extensions" (just add the word "extension" behind the extension ideas) to make the list look better and also allows for the "Propose your own idea" to be in the ideas list.

So below the welcome paragraph the clickable list of ideas will look like this:

- User mentions
- REST API
- Push notifications
- Social Sharing
- Admin Control Panel UI/UX
- Converter Framework
- Advanced Styleguide driven development(SDD) system
- Improved moderator tools
- Advertisement Management Extension
- Human Readable URLs Extension
- Propose your own idea

**Instructions Page**
4. In the mentor list, please remove the [lead] tag order the mentors on last name.

**Comment by VSEphpbb** [comment]
I would update the prerequisites for extensions to:
Object-oriented PHP, SQL, JavaScript/jQuery, CSS, GIT

**Pull request merged**
