### PR TITLE
extension writing - permissions

### PR DESCRIPTION
**Pull request by VSEphpbb**
PHPBB-1078

### CODE REVIEW

**Comment by VSEphpbb** [comment]
Added more tutoring, mainly because of this discussion in phpbb-dev:
>brunoais: Any example on how to add new language keys for permissions from extensions?
brunoais: nickvergessen, ^
nickvergessen: create a language file that is prefixed with permission_
nickvergessen: just like in 3.0
brunoais: Just that?
brunoais: Not any of the stuff that seem to be here? https://www.phpbb.com/extensions/writing/#a-language-files
nickvergessen: for translating, yes
brunoais: It tells about using the core.permissions event
brunoais: I don't really get why
nickvergessen: Pro-Tip: Language files can be given any name. However, language files prefixed with permissions_ or info_acp_ will be auto loaded for permission and ACP module name variables, respectively.
brunoais: Yeah, I noticed that
brunoais: but that kinda confused me
nickvergessen: paul999: ^ needs some adjustments?
brunoais: What's the "core.permissions" event for, then?
nickvergessen: it also says "For example:"
brunoais: True
nickvergessen: and then there is no sample
nickvergessen: so I assume its just left over
brunoais: No example doesn't really help <_>
nickvergessen: VSE: ^ did you write it?
brunoais: Acme extension doesn't show it
paul999: nickvergessen: create a issue?
paul999: ￼
nickvergessen: well adding a permission is not "basic" stuff
brunoais: IIRC all of the other staff examples don't include working with permissions
nickvergessen: and acme is basic only
brunoais: I c...
brunoais: In my case, what I need for now is simple stuff ￼
VSE: nickvergessen: not sure what's confusing about that
brunoais: There's no real explanation on how to add a new permission to the permissions list
nickvergessen: the event is wrong info 
brunoais: my permission is on misc ATM, btw
nickvergessen: and it refers to an unexisting example
paul999: brunoais: The wiki provide info how to add new permissions itself (In migrations)? 
VSE: brunoais: yes there is: https://wiki.phpbb.com/Migrations/Tools/Permission
brunoais: Yes
brunoais: it says how to add them ^^
nickvergessen: + https://github.com/phpbb/phpbb/blob/develop/phpBB/language/en/acp/permissions_phpbb.php#L40-L47
nickvergessen: brunoais: ^
brunoais: *checking...*
brunoais: I read that, yes ￼
nickvergessen: okay
nickvergessen: so you need the event to add the logic
brunoais: But it is incomplete
nickvergessen: and the file is only for translating

**Comment by VSEphpbb** [comment]
@nickvergessen If you wanna take a look ;)

**Comment by nickvergessen** [comment]
GJ :+1:

**Comment by michaelcullum** [comment]
@DavidIQ Merge if this is okay (Green button). I'll handle the rest (And do the previous extension pr simultaneously).

**Pull request merged**
